/* 🤖 this file was generated by svg-to-ts */

import { Svg } from './icons/svg.model';

export type SvgNameSubset<T extends Readonly<Svg[]>> = T[number]['name'];

export * from './icons/svg-arrow-down.icon';
export * from './icons/svg-arrow-up.icon';
export * from './icons/svg-minus.icon';
export * from './icons/svg-plus.icon';
export * from './icons/svg.model';
