/* 🤖 this file was generated by svg-to-ts */
export const svgPlus: {
  name: 'plus';
  data: string;
} = {
  name: 'plus',
  data: `<svg version="1.1" xmlns="http://www.w3.org/2000/svg"><symbol id="svg__plus" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></symbol></svg>`
};
