/* 🤖 this file was generated by svg-to-ts */
export const svgMinus: {
  name: 'minus';
  data: string;
} = {
  name: 'minus',
  data: `<svg version="1.1" xmlns="http://www.w3.org/2000/svg"><symbol id="svg__minus" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/></symbol></svg>`
};
